displayName: Rewrite Header
summary: Rewrites the HTTP response headers by replacing a search regex by a replacement string.
type: middleware
import: github.com/XciD/traefik-plugin-rewrite-headers
compatibility: TODO
testData:
  rewrites:
    - header: Location
      regex: "^http://(.+)$"
      replacement: "https://$1"
